PES-2384:  Cannot change shipment method in settings in Joomla 3
Zasilkovna/virtuemart3 pull request #103
Opened 2024-11-19 08:57 UTC by DBelka

Added a condition to check Joomla version in order to make the correct DB transaction.

2024-11-20 09:50 UTC, jan-potuznik-z commented on zasilkovna.php
>                  // To save parameters in VirtueMart 4
Komentář mluví o VM, nejde, vzhledem k podímnce o verzi Joomla?

2024-11-20 09:52 UTC, DBelka commented on zasilkovna.php
>                  // To save parameters in VirtueMart 4
Mas pravdu, opraveno.

2024-11-20 11:33 UTC, zemekoule requested changes

2024-11-20 12:05 UTC, DBelka commented on zasilkovna.php
> +                    foreach ($table->_varsToPushParam as $k => $v) {
Upraveno.

2024-11-21 10:46 UTC, zemekoule approved these changes

2024-11-21 10:46 UTC, merged