PES-1243 Add description for API pass and Sender in configuration
Zasilkovna/virtuemart3 pull request #46
Opened 2023-02-21 14:37 UTC by Mrakor

Add helping information for users
Add basic length validation of API pass

2023-02-22 08:51 UTC, jan-potuznik-z commented on media/admin/com_virtuemart/controllers/zasilkovna.php
> +            $msg = JText::_('PLG_VMSHIPMENT_PACKETERY_API_PASS_INVALID');
Proměnné prosím inicializuj. Preferoval bych $message a $messageType.

2023-02-22 08:51 UTC, jan-potuznik-z commented on media/admin/com_virtuemart/views/zasilkovna/tmpl/default_config.php
> +        <tr><td colspan="2">&nbsp;</td></tr>
Nemohli bychom na to použít CSS?

2023-02-23 09:12 UTC, packeta requested changes

2023-02-23 09:12 UTC, packeta commented on media/admin/cs-CZ.plg_vmshipment_zasilkovna.ini
> +PLG_VMSHIPMENT_PACKETERY_FIND_API_PASS_IN_CS="Heslo API naleznete v klientské sekci Zásilkovny v části <a href=\"https://client.packeta.com/cs/support\" target=\"_blank\">Klientská podpora</a>"
Do překladů nepatří html kód.  Prosím nahradit zástupným symbolem, jako to např. děláme v Shoptetu

2023-02-23 09:12 UTC, packeta commented on media/admin/com_virtuemart/controllers/zasilkovna.php
>          if(JRequest::getCmd('task') == 'apply') {
Když už se v té metodě save hrabeme,  tak prosím opravit na striktní porovnání a dát mezeru za if (...

2023-02-23 09:12 UTC, packeta commented on media/admin/com_virtuemart/controllers/zasilkovna.php
> +        $message = null;
tady by se nabízelo vytvořit value object, který bude přijímat message a typ a uvnitř budou definovány typy message, které lze použít.  Sjednotí to tak použití message.

2023-02-24 20:36 UTC, merged